---
- name: Sudo is installed
  ansible.builtin.dnf:
    name: sudo
    state: latest

- name: Git is installed
  ansible.builtin.dnf:
    name: git
    state: latest

- name: Make/CMake/rpmbuild is installed
  ansible.builtin.dnf:
    name:
      - cmake
      - make
      - rpm-build
    state: latest

- name: GCC is installed
  ansible.builtin.dnf:
    name:
      - gcc
      - gcc-c++
    state: latest

- name: Python3 is installed
  ansible.builtin.dnf:
    name:
      - python3
      - python3-virtualenv
    state: latest

- name: Static analysis tools are installed
  ansible.builtin.dnf:
    name:
      - cppcheck
      - clang-tools-extra
    state: latest
