stages:
  - prepare
  - check
  - build
  - test
  - upload

default:
  image: $DOCKER_IMAGE:ol8
  tags: [$DOCKER_IMAGE_TAG]
  interruptible: true

include:
  - local: 'ci/prepare.gitlab-ci.yaml'
  - local: 'ci/check.gitlab-ci.yaml'
  - local: 'ci/build.gitlab-ci.yaml'
  - local: 'ci/test.gitlab-ci.yaml'
  - local: 'ci/upload.gitlab-ci.yaml'

variables:
  GIT_STRATEGY: clone
  DOCKER_SHELL_TAG: docker-ci-shell
  DOCKER_IMAGE_TAG: docker-ci-image
  DOCKER_IMAGE: $CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG
