[tool.black]
line-length = 120

[tool.pylint.messages_control]
max-line-length = 120
disable = "E0401, R0801"

[tool.pylint.design]
max-attributes=10
max-args=10

[tool.pytest.ini_options]
pythonpath = [
  "tools/ft-profiler/src",
]
