[tool.black]
line-length = 120

[tool.pylint.messages_control]
max-line-length = 120
disable = "E0401, R0801"

[tool.pylint.design]
max-attributes=10
max-args=10

[tool.pylint.imports]
known-third-party = ["docker"]

[tool.pytest.ini_options]
pythonpath = [
  "tools/ft-profiler/src",
  "tools/ft-analyzer",
  "tools/ft-generator/tests",
]
markers = [
  "dev: development tests",
  "dev_docker: development tests using docker",
  "validation: probe validation tests",
]
log_cli = "true"
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
addopts = "-s"

[tool.isort]
profile = "black"
known_third_party = ["docker"]
