---
- name: Detect running nftables
  ansible.builtin.systemd:
    name: "nftables.service"
  register: nftables_service

- name: Reset nftables (reload ruleset)
  ansible.builtin.systemd:
    name: "nftables.service"
    state: "reloaded"
  when: nftables_service.status.ActiveState == 'active'

- name: Detect input chain name (OL8)
  set_fact:
    input_chain: "INPUT"
  when: ansible_distribution_major_version == "8"

- name: Allow ports in nftables
  ansible.builtin.shell: nft add rule inet firewall {{ input_chain }} {{ item.1 }} dport {{ item.0 | int }} accept
  with_list: "{{ firewall_ports }}"
  when: nftables_service.status.ActiveState == 'active'
