---
- name: Nemea repository is installed
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:group_CESNET:NEMEA
    description: Copr repo for NEMEA owned by @CESNET
    baseurl: "{{ url }}/epel-{{ ansible_distribution_major_version }}-$basearch/"
    skip_if_unavailable: yes
    gpgcheck: yes
    gpgkey: "{{ url }}/pubkey.gpg"
    repo_gpgcheck: no
    enabled: yes
  vars:
    url: https://download.copr.fedorainfracloud.org/results/@CESNET/NEMEA
