---
- name: libpcap library is installed
  ansible.builtin.dnf:
    name:
      - libpcap
      - libpcap-devel
    state: latest

- name: xxhash library is installed
  ansible.builtin.dnf:
    name:
      - xxhash-libs
      - xxhash-devel
    state: latest

- name: nfb-framework is installed
  ansible.builtin.dnf:
    name: nfb-framework
    state: latest
