---
- name: libpcap library is installed
  ansible.builtin.dnf:
    name:
      - libpcap
      - libpcap-devel
    state: latest

- name: xxhash library is installed
  ansible.builtin.dnf:
    name:
      - xxhash-libs
      - xxhash-devel
    state: latest

- name: glpk library is installed
  ansible.builtin.dnf:
    name:
      - glpk
      - glpk-devel
    state: latest

- name: libbpf library is installed
  ansible.builtin.dnf:
    name:
      - libbpf
      - libbpf-devel
    state: latest

- name: libxdp library is installed
  ansible.builtin.dnf:
    name:
      - libxdp
      - libxdp-devel
    state: latest
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int > 8

- name: nfb-framework is installed
  ansible.builtin.dnf:
    name: nfb-framework
    state: latest
