---
- name: PowerTools repository is enabled (RHEL/Rocky/etc.)
  ansible.builtin.command: dnf config-manager --set-enabled powertools
  args:
    warn: false
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'OracleLinux'

- name: PowerTools repository is enabled (Oracle Linux)
  ansible.builtin.command: dnf config-manager --set-enabled {{ repo }}
  args:
    warn: false
  vars:
    repo: "ol{{ ansible_distribution_major_version }}_codeready_builder"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'OracleLinux'
