.build:
  stage: build
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script: [make CFLAGS="-Werror"]
  artifacts:
    paths: [build]
    exclude: [build/**/*.o]

build [Oracle Linux 8]:
  extends: .build
  variables: { DOCKER_TAG: ol8 }

build [CentOS Stream 8]:
    extends: .build
    variables: { DOCKER_TAG: centos8 }

.rpmbuild:
  stage: build
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script: [make rpm]
  artifacts:
    paths: [build/pkg/rpm/rpmbuild/RPMS/*/*.rpm]

rpmbuild [Oracle Linux 8]:
    extends: .rpmbuild
    variables: { DOCKER_TAG: ol8 }

rpmbuild [CentOS Stream 8]:
    extends: .rpmbuild
    variables: { DOCKER_TAG: centos8 }
