.build:
  stage: build
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script: [make]
  variables:
    CFLAGS: -Werror
    CXXFLAGS: -Werror
    CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DENABLE_NFB=ON

build [Oracle Linux 8]:
  extends: .build
  variables: { DOCKER_TAG: ol8 }

build [Oracle Linux 9]:
  extends: .build
  variables: { DOCKER_TAG: ol9 }

build [Rocky Linux 9]:
  extends: .build
  variables: { DOCKER_TAG: rl9 }

.rpmbuild:
  stage: build
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script:
    - make rpm
    - mkdir $DOCKER_TAG
    - mv build/pkg/rpm/rpmbuild/RPMS $DOCKER_TAG
  variables:
    CMAKE_ARGS: -DENABLE_NFB=ON
  artifacts:
    paths: [$DOCKER_TAG/RPMS/*/*.rpm]
    expire_in: 1 week

rpmbuild [Oracle Linux 8]:
  extends: .rpmbuild
  variables: { DOCKER_TAG: ol8 }

rpmbuild [Oracle Linux 9]:
    extends: .rpmbuild
    variables: { DOCKER_TAG: ol9 }

rpmbuild [Rocky Linux 9]:
    extends: .rpmbuild
    variables: { DOCKER_TAG: rl9 }

python package build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/tools/ft-profiler
    - pipenv run python3 -m build
    - cd $CI_PROJECT_DIR/tools/ft-profile-trimmer
    - pipenv run python3 -m build
  artifacts:
    paths: [tools/**/*.whl, tools/**/*.tar.gz]
    expire_in: 1 week
