.install:
  stage: test
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script:
    - sudo yum install -y --setopt='tsflags=' build/pkg/rpm/rpmbuild/RPMS/*/*.rpm
  variables: { GIT_STRATEGY: none }

install [Oracle Linux 8]:
    extends: .install
    needs: ["rpmbuild [Oracle Linux 8]"]
    variables: { DOCKER_TAG: ol8 }

install [CentOS Stream 8]:
    extends: .install
    needs: ["rpmbuild [CentOS Stream 8]"]
    variables: { DOCKER_TAG: centos8 }
