.install:
  stage: test
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script:
    - sudo yum install -y --setopt='tsflags=' $DOCKER_TAG/RPMS/*/*.rpm
  variables: { GIT_STRATEGY: none }

install [Oracle Linux 8]:
  extends: .install
  needs: ["rpmbuild [Oracle Linux 8]"]
  variables: { DOCKER_TAG: ol8 }

install [CentOS Stream 8]:
  extends: .install
  needs: ["rpmbuild [CentOS Stream 8]"]
  variables: { DOCKER_TAG: centos8 }

install [Oracle Linux 9]:
    extends: .install
    needs: ["rpmbuild [Oracle Linux 9]"]
    variables: { DOCKER_TAG: ol9 }

install [Rocky Linux 8]:
    extends: .install
    needs: ["rpmbuild [Rocky Linux 9]"]
    variables: { DOCKER_TAG: rl9 }

pytest:
  stage: test
  script:
    - pipenv run pytest -v -s -m "not dev and not dev_docker" | tee pytest.log
  artifacts:
    paths: [ pytest.log ]
    when: always
