upload python packages:
  stage: upload
  needs: ["python package build", "pytest", "ctest"]
  script:
    - |
      REPO_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
      export TWINE_USERNAME=gitlab-ci-token
      export TWINE_PASSWORD=${CI_JOB_TOKEN}

      set +e  # allow errors (job ends if return code isn't 0 by default)
      pipenv run python3 -m twine upload --verbose --skip-existing --repository-url $REPO_URL tools/**/dist/*
  only: ['main']

upload rpm package:
  stage: upload
  tags: [ci-shell]
  needs: ["rpmbuild [Oracle Linux 8]", "rpmbuild [Oracle Linux 9]", "pytest", "ctest"]
  script:
    - |
        umask 0002
        mkdir -p $CI_REPO_PATH/8
        mkdir -p $CI_REPO_PATH/9
        rsync -ur --chmod=g+w --delete ol8/RPMS/x86_64/* $CI_REPO_PATH/8
        rsync -ur --chmod=g+w --delete ol9/RPMS/x86_64/* $CI_REPO_PATH/9
        find $CI_REPO_PATH -mindepth 1 -maxdepth 2 -type d -exec createrepo --update '{}' \;
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main" && $CI_REPO_PATH
