---
- hosts: localhost
  connection: local
  become: yes
  roles:
    - role: python_upgrade
      when: ansible_distribution_major_version | int == 8
    - common_tools
    - cpp_dependencies
    - cpp_development
    - python_tools
    - nfb_framework
